export interface NavItemProps {
  id: string;
  messageId: string;
  title: string;
  icon?: string;
  exact?: boolean;
  url?: string;
  as?: string;
  type?: string;
  count?: number;
  color?: string;
  auth?: string[];
  children?: NavItemProps[] | NavItemProps;
}

const routesConfig: NavItemProps[] = [
  {
    id: 'app',
    title: 'Application',
    messageId: 'sidebar.application',
    type: 'group',
    children: [
      {
        id: 'dashboard',
        title: 'Dashboard',
        messageId: 'sidebar.app.dashboard.analytics',
        type: 'item',
        icon: 'dashboard',
        url: '/dashboards/analytics',
      },
      {
        id: 'adminweb',
        title: 'Admin Web',
        messageId: 'Admin Web',
        type: 'collapse',
        icon: 'dvr',
        children: [
          {
            id: 'artikel',
            title: 'Artikel',
            messageId: 'Artikel',
            type: 'item',
            url: '/admin-web/artikel',
          },
        ],
      },
      // {
      //   id: 'metrics',
      //   title: 'Metrics',
      //   messageId: 'sidebar.app.metrics',
      //   type: 'item',
      //   icon: 'insert_chart',
      //   url: '/dashboards/metrics',
      // },
      // {
      //   id: 'widgets',
      //   title: 'Widgets',
      //   messageId: 'sidebar.app.widgets',
      //   type: 'item',
      //   icon: 'widgets',
      //   url: '/dashboards/widgets',
      // },
    ],
  },
  // {
  //   id: 'ecommerce',
  //   title: 'Ecommerce',
  //   messageId: 'sidebar.ecommerce',
  //   type: 'collapse',
  //   icon: 'shopping_cart',
  //   children: [
  //     {
  //       id: 'products',
  //       title: 'Products',
  //       messageId: 'sidebar.ecommerce.products',
  //       type: 'item',
  //       url: '/crema/ecommerce/products',
  //     },
  //     {
  //       id: 'product_detail',
  //       title: 'Product Detail',
  //       messageId: 'sidebar.ecommerce.productDetail',
  //       type: 'item',
  //       url: '/crema/ecommerce/product_detail/[...all]',
  //       as: '/ecommerce/product_detail/1',
  //     },
  //     {
  //       id: 'orders',
  //       title: 'Orders',
  //       messageId: 'sidebar.ecommerce.orders',
  //       type: 'item',
  //       url: '/crema/ecommerce/orders',
  //     },
  //     {
  //       id: 'customers',
  //       title: 'Customers',
  //       messageId: 'sidebar.ecommerce.customers',
  //       type: 'item',
  //       url: '/crema/ecommerce/customers',
  //     },
  //     {
  //       id: 'cart',
  //       title: 'Cart',
  //       messageId: 'sidebar.ecommerce.cart',
  //       type: 'item',
  //       url: '/crema/ecommerce/cart',
  //     },
  //     {
  //       id: 'checkout',
  //       title: 'Checkout',
  //       messageId: 'sidebar.ecommerce.checkout',
  //       type: 'item',
  //       url: '/crema/ecommerce/checkout',
  //     },
  //     {
  //       id: 'confirmation',
  //       title: 'Confirmation',
  //       messageId: 'sidebar.ecommerce.confirmation',
  //       type: 'item',
  //       url: '/crema/ecommerce/confirmation',
  //     },
  //     {
  //       id: 'invoice-1',
  //       title: 'Invoice 1',
  //       messageId: 'sidebar.ecommerce.invoice1',
  //       type: 'item',
  //       url: '/crema/ecommerce/invoice-1',
  //     },
  //     {
  //       id: 'invoice-2',
  //       title: 'Invoice 2',
  //       messageId: 'sidebar.ecommerce.invoice2',
  //       type: 'item',
  //       url: '/crema/ecommerce/invoice-2',
  //     },
  //   ],
  // },
  // {
  //   id: 'apps',
  //   title: 'Apps',
  //   messageId: 'sidebar.apps',
  //   type: 'collapse',
  //   icon: 'apps',
  //   children: [
  //     {
  //       id: 'mail',
  //       title: 'Mail',
  //       messageId: 'sidebar.apps.mail',
  //       type: 'item',
  //       count: 4,
  //       url: '/crema/apps/mail',
  //     },
  //     {
  //       id: 'todo',
  //       title: 'ToDo',
  //       messageId: 'sidebar.apps.todo',
  //       type: 'item',
  //       count: 6,
  //       color: '#48bb78',
  //       url: '/crema/apps/todo',
  //     },
  //     {
  //       id: 'contact',
  //       title: 'Contact',
  //       messageId: 'sidebar.apps.contact',
  //       type: 'item',
  //       url: '/crema/apps/contact',
  //     },
  //     {
  //       id: 'scrum-board',
  //       title: 'Scrum Board',
  //       messageId: 'sidebar.apps.scrumboard',
  //       type: 'item',
  //       url: '/crema/apps/scrum-board',
  //     },
  //     {
  //       id: 'chat',
  //       title: 'Chat',
  //       messageId: 'sidebar.apps.chat',
  //       type: 'item',
  //       url: '/crema/apps/chat',
  //     },
  //     {
  //       id: 'wall',
  //       title: 'Wall',
  //       messageId: 'sidebar.apps.wall',
  //       type: 'item',
  //       url: '/crema/apps/wall',
  //     },
  //   ],
  // },
  // {
  //   id: 'pages',
  //   title: 'Pages',
  //   messageId: 'sidebar.pages',
  //   type: 'group',
  //   children: [
  //     {
  //       id: 'timeline',
  //       title: 'Time Line',
  //       messageId: 'sidebar.pages.timeLine',
  //       type: 'item',
  //       icon: 'timeline',
  //       url: '/crema/third-party/time-line',
  //     },
  //     {
  //       id: 'extra-pages',
  //       title: 'Extra Pages',
  //       messageId: 'sidebar.pages.extraPages',
  //       type: 'collapse',
  //       icon: 'work_outline',
  //       children: [
  //         {
  //           id: 'about-us',
  //           title: 'About Us',
  //           messageId: 'sidebar.pages.extraPages.aboutUs',
  //           type: 'item',
  //           url: '/crema/extra-pages/about-us',
  //         },
  //         {
  //           id: 'knowledge-base',
  //           title: 'Knowledge Base',
  //           messageId: 'sidebar.pages.extraPages.knowledgeBase',
  //           type: 'item',
  //           url: '/crema/extra-pages/knowledge-base',
  //         },
  //         {
  //           id: 'portfolio',
  //           title: 'Portfolio',
  //           messageId: 'sidebar.pages.extraPages.portfolio',
  //           type: 'item',
  //           url: '/crema/extra-pages/portfolio',
  //         },
  //         {
  //           id: 'faq',
  //           title: 'FAQ',
  //           messageId: 'sidebar.pages.extraPages.faq',
  //           type: 'item',
  //           url: '/crema/extra-pages/faq',
  //         },
  //       ],
  //     },
  //     {
  //       id: 'user',
  //       title: 'User Pages',
  //       messageId: 'sidebar.pages.userPages',
  //       type: 'collapse',
  //       icon: 'verified_user',
  //       children: [
  //         {
  //           id: 'sign-in-1',
  //           title: 'SignIn-1',
  //           messageId: 'sidebar.pages.userPages.signIn1',
  //           type: 'item',
  //           url: '/crema/user/sign-in-1',
  //         },
  //         {
  //           id: 'sign-in-2',
  //           title: 'SignIn-2',
  //           messageId: 'sidebar.pages.userPages.signIn2',
  //           type: 'item',
  //           url: '/crema/user/sign-in-2',
  //         },
  //         {
  //           id: 'sign-up-1',
  //           title: 'SignUp-1',
  //           messageId: 'sidebar.pages.userPages.signUp1',
  //           type: 'item',
  //           url: '/crema/user/sign-up-1',
  //         },
  //         {
  //           id: 'sign-up-2',
  //           title: 'SignUp-2',
  //           messageId: 'sidebar.pages.userPages.signUp2',
  //           type: 'item',
  //           url: '/crema/user/sign-up-2',
  //         },
  //         {
  //           id: 'forgot-password-1',
  //           title: 'Forgot Password-1',
  //           messageId: 'sidebar.pages.userPages.forgetPassword1',
  //           type: 'item',
  //           url: '/crema/user/forgot-password-1',
  //         },
  //         {
  //           id: 'forgot-password-2',
  //           title: 'Forgot Password-2',
  //           messageId: 'sidebar.pages.userPages.forgetPassword2',
  //           type: 'item',
  //           url: '/crema/user/forgot-password-2',
  //         },
  //         {
  //           id: 'reset-password-1',
  //           title: 'Reset Password-1',
  //           messageId: 'sidebar.pages.userPages.resetPassword1',
  //           type: 'item',
  //           url: '/crema/user/reset-password-1',
  //         },
  //         {
  //           id: 'reset-password-2',
  //           title: 'Reset Password-2',
  //           messageId: 'sidebar.pages.userPages.resetPassword2',
  //           type: 'item',
  //           url: '/crema/user/reset-password-2',
  //         },
  //         {
  //           id: 'lock-1',
  //           title: 'Lock Screen-1',
  //           messageId: 'sidebar.pages.userPages.lockScreen1',
  //           type: 'item',
  //           url: '/crema/user/lock-1',
  //         },
  //         {
  //           id: 'lock-2',
  //           title: 'Lock Screen-2',
  //           messageId: 'sidebar.pages.userPages.lockScreen2',
  //           type: 'item',
  //           url: '/crema/user/lock-2',
  //         },
  //       ],
  //     },
  //     {
  //       id: 'list-type',
  //       title: 'User List',
  //       messageId: 'sidebar.pages.userList',
  //       type: 'collapse',
  //       icon: 'view_list',
  //       children: [
  //         {
  //           id: 'morden',
  //           title: 'Modern',
  //           messageId: 'sidebar.pages.userList.modern',
  //           type: 'item',
  //           url: '/crema/list-type/morden',
  //         },
  //         {
  //           id: 'standard',
  //           title: 'Standard',
  //           messageId: 'sidebar.pages.userList.standard',
  //           type: 'item',
  //           url: '/crema/list-type/standard',
  //         },
  //         {
  //           id: 'flat',
  //           title: 'Flat',
  //           messageId: 'sidebar.pages.userList.flat',
  //           type: 'item',
  //           url: '/crema/list-type/flat',
  //         },
  //       ],
  //     },
  //     {
  //       id: 'error-pages',
  //       title: 'Error Pages',
  //       messageId: 'sidebar.pages.errorPages',
  //       type: 'collapse',
  //       icon: 'report',
  //       children: [
  //         {
  //           id: 'error-404',
  //           title: '404',
  //           messageId: 'sidebar.pages.errorPages.404',
  //           type: 'item',
  //           url: '/crema/error-pages/error-404',
  //         },
  //         {
  //           id: 'error-500',
  //           title: '500',
  //           messageId: 'sidebar.pages.errorPages.500',
  //           type: 'item',
  //           url: '/crema/error-pages/error-500',
  //         },
  //         {
  //           id: 'maintenance',
  //           title: 'Maintenance',
  //           messageId: 'sidebar.pages.errorPages.maintenance',
  //           type: 'item',
  //           url: '/crema/error-pages/maintenance',
  //         },
  //         {
  //           id: 'coming-soon',
  //           title: 'Coming Soon',
  //           messageId: 'sidebar.pages.errorPages.comingSoon',
  //           type: 'item',
  //           url: '/crema/error-pages/coming-soon',
  //         },
  //       ],
  //     },
  //     {
  //       id: 'multi-level',
  //       title: 'Multi Level',
  //       messageId: 'sidebar.multiLevel',
  //       type: 'collapse',
  //       icon: 'menu',
  //       children: [
  //         {
  //           id: 'level-1',
  //           title: 'Level 1',
  //           messageId: 'sidebar.multiLevel.level1',
  //           type: 'item',
  //           url: '/crema/menu-level-1',
  //         },
  //         {
  //           id: 'level-2',
  //           title: 'Level 1',
  //           messageId: 'sidebar.multiLevel.level1',
  //           type: 'collapse',
  //           children: [
  //             {
  //               id: 'level-2-1',
  //               title: 'Level 2',
  //               messageId: 'sidebar.multiLevel.level2',
  //               type: 'item',
  //               url: '/crema/menu-level-2-1',
  //             },
  //             {
  //               id: 'level-2-2',
  //               title: 'Level 2',
  //               messageId: 'sidebar.multiLevel.level2',
  //               type: 'item',
  //               url: '/crema/menu-level-2-2',
  //             },
  //           ],
  //         },
  //         {
  //           id: 'level-3',
  //           title: 'Level 1',
  //           messageId: 'sidebar.multiLevel.level1',
  //           type: 'collapse',
  //           children: [
  //             {
  //               id: 'level-3-1',
  //               title: 'Level 2',
  //               messageId: 'sidebar.multiLevel.level2',
  //               type: 'collapse',
  //               children: [
  //                 {
  //                   id: 'level-3-1-1',
  //                   title: 'Level 3',
  //                   messageId: 'sidebar.multiLevel.level3',
  //                   type: 'item',
  //                   url: '/crema/menu-level-3-1-1',
  //                 },
  //                 {
  //                   id: 'level-3-1-2',
  //                   title: 'Level 3',
  //                   messageId: 'sidebar.multiLevel.level3',
  //                   type: 'item',
  //                   url: '/crema/menu-level-3-1-2',
  //                 },
  //               ],
  //             },
  //             {
  //               id: 'level-3-2',
  //               title: 'Level 2',
  //               messageId: 'sidebar.multiLevel.level2',
  //               type: 'collapse',
  //               children: [
  //                 {
  //                   id: 'level-3-2-1',
  //                   title: 'Level 3',
  //                   messageId: 'sidebar.multiLevel.level3',
  //                   type: 'item',
  //                   url: '/crema/menu-level-3-2-1',
  //                 },
  //                 {
  //                   id: 'level-3-2-2',
  //                   title: 'Level 3',
  //                   messageId: 'sidebar.multiLevel.level3',
  //                   type: 'item',
  //                   url: '/crema/menu-level-3-2-2',
  //                 },
  //               ],
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //   ],
  // },
];
export default routesConfig;
