FROM node:14.16.0-stretch-slim as build
WORKDIR /app
RUN yarn global add serve
COPY package*.json ./
RUN yarn install --production
COPY . .
RUN yarn build-staging
CMD ["serve", "-s", "build", "-l", "5000"]